# https://stackoverflow.com/a/70711156/1534675
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'nodejs-api/**'
              - 'docker-compose.yml'
              - 'docker-compose.test.backend.yml'
              - 'run-backend-tests.sh'
      # run only if 'backend' files were changed
      - name: backend tests
        if: steps.filter.outputs.backend == 'true'
        run: echo "Backend tests"
      # run only if not 'backend' files were changed
      - name: not backend tests
        if: steps.filter.outputs.backend != 'true'
        run: echo "NOT Backend tests"
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ./run-backend-tests.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
